version: "3.8"
services:
  server:
    build:
      context: ./server
    container_name: server-app
    ports:
      - "9000:9000"
    networks:
      - app-network

  client:
    build:
      context: ./client
    container_name: client-app
    ports:
      - "3000:80"
    environment:
      - VITE_BACKEND_URL=http://server-app:9000
    networks:
      - app-network

networks:
  app-network:
